package com.bank.paymentinitiation.adapter.in.rest;

import com.bank.paymentinitiation.adapter.in.rest.mapper.PaymentOrderRestMapper;
import com.bank.paymentinitiation.application.service.PaymentOrderReferenceGenerator;
import com.bank.paymentinitiation.domain.model.PaymentOrder;
import com.bank.paymentinitiation.domain.port.in.InitiatePaymentOrderUseCase;
import com.bank.paymentinitiation.domain.port.in.RetrievePaymentOrderUseCase;
import com.bank.paymentinitiation.generated.api.PaymentOrdersApi;
import com.bank.paymentinitiation.generated.model.InitiatePaymentOrderRequest;
import com.bank.paymentinitiation.generated.model.InitiatePaymentOrderResponse;
import com.bank.paymentinitiation.generated.model.PaymentOrderStatusResponse;
import com.bank.paymentinitiation.generated.model.RetrievePaymentOrderResponse;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller for Payment Orders.
 * 
 * This controller implements the PaymentOrdersApi interface generated by OpenAPI Generator.
 * It handles HTTP requests and delegates to application services (use cases).
 * 
 * Responsibilities:
 * - Receive HTTP requests (POST, GET)
 * - Validate request DTOs
 * - Generate payment order references
 * - Map between DTOs and domain models
 * - Call use cases
 * - Return HTTP responses
 * 
 * This is the driving adapter (inbound adapter) in the Hexagonal Architecture.
 * It adapts HTTP requests to domain use cases.
 */
@RestController
@RequiredArgsConstructor
@Slf4j
public class PaymentOrdersController implements PaymentOrdersApi {
    
    private final InitiatePaymentOrderUseCase initiatePaymentOrderUseCase;
    private final RetrievePaymentOrderUseCase retrievePaymentOrderUseCase;
    private final PaymentOrderRestMapper mapper;
    private final PaymentOrderReferenceGenerator referenceGenerator;
    
    @Override
    public ResponseEntity<InitiatePaymentOrderResponse> initiatePaymentOrder(
            @Valid InitiatePaymentOrderRequest initiatePaymentOrderRequest) {
        
        log.info("Received request to initiate payment order with external reference: {}", 
            initiatePaymentOrderRequest.getExternalReference());
        
        // Generate payment order reference
        String paymentOrderReference = referenceGenerator.generate();
        log.debug("Generated payment order reference: {}", paymentOrderReference);
        
        // Map DTO → domain
        PaymentOrder domainOrder = mapper.toDomain(initiatePaymentOrderRequest, paymentOrderReference);
        
        // Call use case
        PaymentOrder initiatedOrder = initiatePaymentOrderUseCase.initiate(domainOrder);
        
        // Map domain → response DTO
        InitiatePaymentOrderResponse response = mapper.toInitiateResponse(initiatedOrder);
        
        log.info("Payment order initiated successfully with reference: {}", 
            response.getPaymentOrderReference());
        
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }
    
    @Override
    public ResponseEntity<RetrievePaymentOrderResponse> retrievePaymentOrder(String id) {
        
        log.info("Received request to retrieve payment order with reference: {}", id);
        
        // Call use case
        PaymentOrder paymentOrder = retrievePaymentOrderUseCase.retrieve(id);
        
        // Map domain → response DTO
        RetrievePaymentOrderResponse response = mapper.toRetrieveResponse(paymentOrder);
        
        log.debug("Payment order retrieved successfully: {}", id);
        
        return ResponseEntity.ok(response);
    }
    
    @Override
    public ResponseEntity<PaymentOrderStatusResponse> retrievePaymentOrderStatus(String id) {
        
        log.info("Received request to retrieve payment order status with reference: {}", id);
        
        // Call use case (retrieve full order to get paymentOrderReference and lastUpdated)
        // Note: Although RetrievePaymentOrderStatusUseCase exists, we use RetrievePaymentOrderUseCase
        // because the response needs paymentOrderReference and lastUpdated, not just the status.
        PaymentOrder paymentOrder = retrievePaymentOrderUseCase.retrieve(id);
        
        // Map domain → response DTO
        PaymentOrderStatusResponse response = mapper.toStatusResponse(paymentOrder);
        
        log.debug("Payment order status retrieved successfully: {}", id);
        
        return ResponseEntity.ok(response);
    }
}
